### ISSUE TITLE
copy/paste error?

### ISSUE THREAD

**Issue by joh-klein** [Marko-M/Inchoo_SocialConnect#25]
is line 131 `$customersByEmail = Mage::helper('inchoo_socialconnect/facebook')` in 

app/code/community/Inchoo/SocialConnect/controllers/GoogleController.php 

a copy/paste bug?

**Comment by Marko-M** [comment]
Hi @joh-klein,
yes, copy paste bug. Will get fixed in develop shortly, master will follow. Thanks for reporting.

Regards

**Comment by Marko-M** [comment]
Fixed in develop, therefore close.
