### ISSUE TITLE
Form Key Missing on `app/design/frontend/base/default/template/inchoo/socialconnect/checkout/onepage/login.phtml`

### ISSUE THREAD

**Issue by dfry22** [Marko-M/Inchoo_SocialConnect#30]
In the `app/design/frontend/base/default/template/inchoo/socialconnect/checkout/onepage/login.phtml` template, there is a missing call to add the formKey to the login. Without this key, the login fails immediately. Adding this line on line 76 will resolve the issue.

                <?php echo $this->getBlockHtml('formkey'); ?>

**Comment by Marko-M** [comment]
Hello @dfry22,
thanks for reporting, this was added to develop by commit ec760774b924f48eb4f853d989c4e6450166403c therefore lets close.

Regards,
Marko
