### ISSUE TITLE
Wrong collection filter in Helper/Facebook.php method getCustomersByFacebookId() ?

### ISSUE THREAD

**Issue by viniciusrtf** [Marko-M/Inchoo_SocialConnect#39]
I'm trying to use getCustomersByFacebookId() in Helper/Facebook.php in my local code.

If I understood this method, it tries to retrieve a collection of all Facebook<->Customer accounts that are already connected. The issue is that $collection always return empty for me, because the last added filter is like this:

```php
if(Mage::getSingleton('customer/session')->isLoggedIn()) {
            $collection->addFieldToFilter(
                'entity_id',
                array('neq' => Mage::getSingleton('customer/session')->getCustomerId())
            );
        }
```
Shouldn't it be `array('eq' => Mage::getSingleton('customer/session')->getCustomerId())` ?

What is this method really trying to do?

**Comment by Marko-M** [comment]
Hello @viniciusrtf,
thanks for reporting, you are right and was fixed by 4e4133c5974abc0c61da68159618b7ceefe79eb0 commit to develop and will end up in master on the next release.

Regards,
Marko
