### ISSUE TITLE
Error in facebook login

### ISSUE THREAD

**Issue by doticonic9** [Marko-M/Inchoo_SocialConnect#40]
sorry, could not retrieve your Facebook first name. Please try again.

showing this error in facebook login.

**Comment by mostmaz** [comment]
i have the very same probleme
could you please guide me for solution if you found it?

**Comment by doticonic9** [comment]
what i was able to find was that this code is working with facebook api v 2.1 .. and if we create a new api now we get api v 2.4 ...

**Comment by Marko-M** [comment]
Hello guys,
thanks for reporting. SocialConnect Facebook API client was created over 2 years ago, thus I'm surprised it held for as long as it did. I'll check it out, and if I confirm this, update will be available till the end of July.

Cheers!

**Comment by doticonic9** [comment]
thank you so much marko, your extension has helped us a lot ... would be waiting for your updates ...
if there's any information required on this please let me know ... would be glad to help you :)
thanks once again :)

**Comment by mostmaz** [comment]
thank you so much would be waiting for your updates

**Comment by dfry22** [comment]
Note the above patch can be used as a short term solution while Marko works on updating the api client. This is working on my affected sites which was experiencing the above error previously

**Comment by doticonic9** [comment]
@dfry22 thank you your code works !! cheers :+1:

**Comment by andhiirawan** [comment]
Hi, all, this is what did and work in my Magento 1.9.1.0 :

edit your file : app\code\community\Inchoo\SocialConnect\Model\Facebook\Info.php
</p>line 97
</p>change 
<pre><code>$this->params</code></pre>
</p>to
<pre><code>
array (
     'fields' =>
     'id,name,first_name,last_name,link,birthday,gender,email,picture.type(large)'
 )
</code></pre>
It will be like this :
<pre><code>
$response = $this->client->api(
                '/me',
                'GET',
                array(
                        'fields' =>
                        'id,name,first_name,last_name,link,birthday,gender,email,picture.type(large)'
                    )
            );
</code></pre>

**Comment by nareshphp1** [comment]
I am facing that not fetching profile image  when login with facebook. Kindly let me know how it can be..
