### ISSUE TITLE
Notice: Undefined property

### ISSUE THREAD

**Issue by JenniferGifford** [Marko-M/Inchoo_SocialConnect#41]
Hi I am currently working on my Woo-commerce shop and keep seeing this on my product pages.  
Notice: Undefined property: stdClass::$post_name in /home/ennifeu1/public_html/wp-includes/template.php on line 317
It appears just above the product and just below as well, on all the product pages.

I am also trying to figure out how to change the heading on the product pages so it doesn't say "Product Category" just the actual name of the category like "A
<img width="543" alt="screenshot 2015-07-20 11 25 29" src="https://cloud.githubusercontent.com/assets/13409931/8768873/15471772-2ed2-11e5-846d-56d7dc5f8561.png">
<img width="806" alt="screenshot 2015-07-20 11 25 19" src="https://cloud.githubusercontent.com/assets/13409931/8768874/1547d3f6-2ed2-11e5-8e6e-8aaee59604c9.png">

ccessories".

This is all very new to me and I have been teaching myself wordpress your help would be greatly appreciated.

Jennifer

**Comment by Marko-M** [comment]
Hello @JenniferGifford,
this is a bug tracker for Magento extension, not for WordPress plugin you reference

Regards,
Marko
