### ISSUE TITLE
Sorry, could not retrieve your Facebook first name. Please try again.

### ISSUE THREAD

**Issue by x3graphics** [Marko-M/Inchoo_SocialConnect#43]
Just installed this on 1.9.2.1 and am getting the this error
Sorry, could not retrieve your Facebook first name. Please try again.

**Comment by R3dRuM** [comment]
Having the same issue running 1.9.1.0.

**Comment by R3dRuM** [comment]
Problem is in  /app/code/community/Inchoo/SocialConnect/Model/Facebook/Info.php _load Method

facebook requires now to add the parameters in a different format like .../me?fields=id,name,first_name

**Comment by x3graphics** [comment]
#42 fixed it for me

**Comment by WebDux** [comment]
Hi,

Could anyboy give the final solution for facebook error: Sorry, could not retrieve your Facebook first name. Please try again.

@R3dRuM has given the idea to solve but I am not developer so I still don't know how to fix that, so could you give more details, please?

Thanks in advance.
