### ISSUE TITLE
Gender on Facebook

### ISSUE THREAD

**Issue by nrebequi** [Marko-M/Inchoo_SocialConnect#53]
When I test the component all the accounts that are created as "male". When I check the controller code Facebook I see this IF

             $ gender = $ info-> getGender ();
             if (empty ($ gender)) {
                 $ gender = null;
             } Else if ($ gender = 'male') {
                 $ gender = 1;
             } Else if ($ gender = 'female') {
                 $ gender = 2;
             }

From what I could test $ info-> getGender () returns female / male, but always its saved like male.
I guess when compared with = and not == error occurs.

**Comment by Marko-M** [comment]
Pull request by @az-iar merged, thanks!
