### ISSUE TITLE
How to fix "Sorry, could not retrieve your Facebook first name. Please try again." , please?

### ISSUE THREAD

**Issue by WebDux** [Marko-M/Inchoo_SocialConnect#57]
Hi,

First, many thanks for your free but perfect Social Connect module.

Now we are using Magento 1.9.2.3 and Social Connect 0.3.7. In fact, when I just installed the Social Connect 0.3.7 on Magento 1.9.2.2, it's ok for Facebook account but after updated Magento 1.9.2.3, it show "Sorry, could not retrieve your Facebook first name. Please try again.".

I ever googled the solution and tryed to add "$this->params[‘fields’] = ‘first_name,last_name,email’;" but it still can't work.

I also tried to change "array('fields' => implode(',', $this->params))" to "array('fields' => 'id,name,first_name,last_name,link,birthday,gender,email,picture.type(large)')" and it can't work also.

So could you help us to fix this problem, please? You can check our store by https://www.herawigs.com .

Many thanks in advance.

**Comment by WebDux** [comment]
Very sorry for this mistake opened issue.

The 0.3.7 version work perfect. I just notice that our theme added 0.2.6 version and I upload the theme directly so it overwrite 0.3.7 so the error happened. Now I have used 0.3.7 overwrite 0.2.6, so everything is right.

Thanks for your perfect module.

**Comment by ahsanaimer** [comment]
Open /app/code/community/Inchoo/SocialConnect/controllers/FacebookController.php

CHANGE 
$userInfo = $client->api('/me');
TO
$userInfo = $client->api('/me','GET', array('fields' => 'id,name,first_name,last_name,link,birthday,gender,email,picture.type(large)'
    ));
